#! /bin/sh                              
### BEGIN INIT INFO
# Provides:          SpiderOak
# Required-Start:    $network $syslog $remote_fs
# Required-Stop:     $network $syslog $remote_fs
# Should-Start:      $named $time
# Should-Stop:       $named $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop the SpiderOak daemon for debian/ubuntu
# Description:       SpiderOak daemon for linux
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON_START=/usr/bin/SpiderOak                                  
DAEMON_STOP=/usr/lib/SpiderOak/SpiderOak                         
NAME="SpiderOak"                                                 
DESC="SpiderOak backup server"

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

set -e

USER=root                
USER_HOME=$(grep ^$USER /etc/passwd | awk -F : '{print $6}')
SPIDEROAKDATADIR=$USER_HOME/.SpiderOak                      
ARGS="--headless"                                           
EXTRA_ARGS=""                                               
NICE=5                                                      
RUNDIR=/var/run/SpiderOak
ARGS="$ARGS $EXTRA_ARGS"

mkdir -p $RUNDIR
chown -R $USER $RUNDIR

case "$1" in
  start)
        if [ -e $RUNDIR/$NAME.pid ]; then
                CHECKPID=$(cat ${RUNDIR}/${NAME}.pid 2>/dev/null 3>/dev/null)
                if [ $(ps -p ${CHECKPID} > /dev/null 2>&1 3>&1; echo $?) -eq 0 ]; then
                        log_success_msg "$DESC already started; use restart instead."
                        exit 1
                else
                        log_success_msg "Removing stale PID file $RUNDIR/$NAME"
                        rm -f $RUNDIR/$NAME.pid
                fi
        fi
        log_daemon_msg "Starting $DESC: $NAME "
        start-stop-daemon --start --background --make-pidfile --pidfile $RUNDIR/$NAME.pid \
                --chuid $USER --nicelevel $NICE --exec $DAEMON_START -- $ARGS
        log_end_msg $?
        ;;
  stop)
        log_daemon_msg "Stopping $DESC: $NAME "
        start-stop-daemon --stop --oknodo \
                --chuid $USER --exec $DAEMON_STOP -- $ARGS
        test -e $RUNDIR/$NAME.pid && rm $RUNDIR/$NAME.pid
        log_end_msg $?
        ;;
  restart|force-reload)
        log_daemon_msg "Restarting $DESC: $NAME "
        start-stop-daemon --stop --oknodo \
                --chuid $USER --exec $DAEMON_STOP -- $ARGS
        test -e $RUNDIR/$NAME.pid && rm $RUNDIR/$NAME.pid
        sleep 3
        start-stop-daemon --start --background --make-pidfile --pidfile $RUNDIR/$NAME.pid \
                --chuid $USER --nicelevel $NICE --exec $DAEMON_START -- $ARGS
        log_end_msg $?
        ;;
  status)
        if [ -e $RUNDIR/$NAME.pid ]; then
                CHECKPID=$(cat ${RUNDIR}/${NAME}.pid 2>/dev/null 3>/dev/null)
                if [ $(ps -p ${CHECKPID} > /dev/null 2>&1 3>&1; echo $?) -eq 0 ]; then
                        log_success_msg "$DESC is running"
                else
                        log_success_msg "$DESC is not running"
                        exit 1
                fi
        fi
        ;;
  *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|force-reload}" >&2
        exit 2
        ;;
esac

exit 0
